name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Fe-Ti/latex-template/actions/miktex@fixup-list-indentation

      - name: Compile full example
        run: |
          initexmf --register-root $PWD
          cd ./full-example
          latexmk -pdf main.tex

      - name: Clean after build full example
        run: |
          cd ./full-example
          latexmk -c ./main.tex

